/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RejectionRouteImport } from './routes/rejection'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PlantRouteImport } from './routes/plant'
import { Route as MonthlyRouteImport } from './routes/monthly'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as DowntimeRouteImport } from './routes/downtime'
import { Route as ControlRouteImport } from './routes/control'
import { Route as IndexRouteImport } from './routes/index'

const RejectionRoute = RejectionRouteImport.update({
  id: '/rejection',
  path: '/rejection',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantRoute = PlantRouteImport.update({
  id: '/plant',
  path: '/plant',
  getParentRoute: () => rootRouteImport,
} as any)
const MonthlyRoute = MonthlyRouteImport.update({
  id: '/monthly',
  path: '/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const DowntimeRoute = DowntimeRouteImport.update({
  id: '/downtime',
  path: '/downtime',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlRoute = ControlRouteImport.update({
  id: '/control',
  path: '/control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/downtime': typeof DowntimeRoute
  '/machines': typeof MachinesRoute
  '/monthly': typeof MonthlyRoute
  '/plant': typeof PlantRoute
  '/production': typeof ProductionRoute
  '/rejection': typeof RejectionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/downtime': typeof DowntimeRoute
  '/machines': typeof MachinesRoute
  '/monthly': typeof MonthlyRoute
  '/plant': typeof PlantRoute
  '/production': typeof ProductionRoute
  '/rejection': typeof RejectionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/control': typeof ControlRoute
  '/downtime': typeof DowntimeRoute
  '/machines': typeof MachinesRoute
  '/monthly': typeof MonthlyRoute
  '/plant': typeof PlantRoute
  '/production': typeof ProductionRoute
  '/rejection': typeof RejectionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/control'
    | '/downtime'
    | '/machines'
    | '/monthly'
    | '/plant'
    | '/production'
    | '/rejection'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/control'
    | '/downtime'
    | '/machines'
    | '/monthly'
    | '/plant'
    | '/production'
    | '/rejection'
  id:
    | '__root__'
    | '/'
    | '/control'
    | '/downtime'
    | '/machines'
    | '/monthly'
    | '/plant'
    | '/production'
    | '/rejection'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlRoute: typeof ControlRoute
  DowntimeRoute: typeof DowntimeRoute
  MachinesRoute: typeof MachinesRoute
  MonthlyRoute: typeof MonthlyRoute
  PlantRoute: typeof PlantRoute
  ProductionRoute: typeof ProductionRoute
  RejectionRoute: typeof RejectionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rejection': {
      id: '/rejection'
      path: '/rejection'
      fullPath: '/rejection'
      preLoaderRoute: typeof RejectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plant': {
      id: '/plant'
      path: '/plant'
      fullPath: '/plant'
      preLoaderRoute: typeof PlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monthly': {
      id: '/monthly'
      path: '/monthly'
      fullPath: '/monthly'
      preLoaderRoute: typeof MonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downtime': {
      id: '/downtime'
      path: '/downtime'
      fullPath: '/downtime'
      preLoaderRoute: typeof DowntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/control': {
      id: '/control'
      path: '/control'
      fullPath: '/control'
      preLoaderRoute: typeof ControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlRoute: ControlRoute,
  DowntimeRoute: DowntimeRoute,
  MachinesRoute: MachinesRoute,
  MonthlyRoute: MonthlyRoute,
  PlantRoute: PlantRoute,
  ProductionRoute: ProductionRoute,
  RejectionRoute: RejectionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
